Fix misleading indentation gcc warning
percpu.c: In function 'cpu_percpu_callback':
percpu.c:61:7: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
       if ( system_state != SYS_STATE_resume )
       ^~
percpu.c:63:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
         break;
         ^~~~~
percpu.c:67:7: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
       if ( system_state != SYS_STATE_suspend )
       ^~
percpu.c:69:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
         break;
         ^~~~~

Fixes: c3109b76d967 ("xen: don't free percpu areas during suspend")

Signed-off-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>