xen/event: add missing inline to evtchn_usable()
The evtchn_usable() function in xen/event.h is defined as static
but lacks the inline keyword.

When included in initialization-only translation units such as
arch/arm/dom0less-build.c, the compiler generates a standalone
copy of the function in a permanent .text section
(.text.evtchn_usable). This causes following build error:

Error: size of arch/arm/dom0less-build.o:.text.evtchn_usable is 0x00000044
make[2]: *** [Rules.mk:277: arch/arm/dom0less-build.init.o] Error 6
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [build.mk:72: arch/arm] Error 2
make: *** [Makefile:626: xen] Error 2

This patch adds the missing inline keyword to evtchn_usable(),
allowing the compiler to properly inline the function into its
init callers or discard it if unused, fixing the build failure.

Signed-off-by: Ruslan Ruslichenko <Ruslan_Ruslichenko@epam.com>